//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FootCenter.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Asiakas
    {
        public int AsiakasID { get; set; }
        public string Sukunimi { get; set; }
        public string Etunimi { get; set; }
        public string Postiosoite { get; set; }
        public string Postitmp { get; set; }
        public string Puhnro { get; set; }
        public string Sposti { get; set; }
    }
}
